### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by q793809050** [Lil-C0der/Vue_CMS#1]
兄弟 为什么我下载下来运行不了呢 说要下载登录页 不懂了

**Comment by Lil-C0der** [comment]
> 兄弟 为什么我下载下来运行不了呢 说要下载登录页 不懂了

https://github.com/Lil-C0der/Vue_CMS_API_SERVER
后台接口和数据库在这个仓库里面 clone到本地以后，运行npm install安装依赖，然后把db文件夹下的mydb.sql导入，再用node app.js把后台服务跑起来。

**Comment by Lil-C0der** [comment]
> 兄弟 为什么我下载下来运行不了呢 说要下载登录页 不懂了

我刚刚试了下 好像不是后台的原因 我现在看看 不好意思

**Comment by q793809050** [comment]
没看到你说的db文件夹呢&nbsp;&nbsp;
只有接口说明的文档 找不到sql文件


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Lil-C0der"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月30日(星期四) 晚上6:18
收件人:&nbsp;"Lil-C0der/Vue_CMS"<Vue_CMS@noreply.github.com&gt;;
抄送:&nbsp;"QQ邮箱"<793809050@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Lil-C0der/Vue_CMS] 问题 (#1)





  
兄弟 为什么我下载下来运行不了呢 说要下载登录页 不懂了
  
https://github.com/Lil-C0der/Vue_CMS_API_SERVER
 后台接口和数据库在这个仓库里面 clone到本地以后，运行npm install安装依赖，然后把db文件夹下的mydb.sql导入，再用node app.js把后台服务跑起来。

**Comment by q793809050** [comment]
To install it, you can run: npm install --save views/login/Login
&nbsp;我是第一次看见这个东西的 你的是文件呀 也不是包 叫下载&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Lil-C0der"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月30日(星期四) 晚上6:34
收件人:&nbsp;"Lil-C0der/Vue_CMS"<Vue_CMS@noreply.github.com&gt;;
抄送:&nbsp;"QQ邮箱"<793809050@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Lil-C0der/Vue_CMS] 问题 (#1)





  
兄弟 为什么我下载下来运行不了呢 说要下载登录页 不懂了
  
我刚刚试了下 好像不是后台的原因 我现在看看 不好意思

**Comment by Lil-C0der** [comment]
> To install it, you can run: npm install --save views/login/Login &nbsp;我是第一次看见这个东西的 你的是文件呀 也不是包 叫下载&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Lil-C0der"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月30日(星期四) 晚上6:34 收件人:&nbsp;"Lil-C0der/Vue_CMS"<Vue_CMS@noreply.github.com&gt;; 抄送:&nbsp;"QQ邮箱"<793809050@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Lil-C0der/Vue_CMS] 问题 (#1) 兄弟 为什么我下载下来运行不了呢 说要下载登录页 不懂了 我刚刚试了下 好像不是后台的原因 我现在看看 不好意思 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

不好意思 现在已经可以了。出现你那个报错是因为git修改文件大小写是不识别的，Login单文件组件原先是小写 后来被我改成大写以后git add的时候不会识别，所以路由的时候会出问题。

**Comment by q793809050** [comment]
我很好奇的是 你的request文件怎么找不到的呢 就是baseURL的文件&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Lil-C0der"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月30日(星期四) 晚上6:50
收件人:&nbsp;"Lil-C0der/Vue_CMS"<Vue_CMS@noreply.github.com&gt;;
抄送:&nbsp;"QQ邮箱"<793809050@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Lil-C0der/Vue_CMS] 问题 (#1)





  
To install it, you can run: npm install --save views/login/Login &nbsp;我是第一次看见这个东西的 你的是文件呀 也不是包 叫下载&nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Lil-C0der"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月30日(星期四) 晚上6:34 收件人:&nbsp;"Lil-C0der/Vue_CMS"<Vue_CMS@noreply.github.com&gt;; 抄送:&nbsp;"QQ邮箱"<793809050@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Lil-C0der/Vue_CMS] 问题 (#1) 兄弟 为什么我下载下来运行不了呢 说要下载登录页 不懂了 我刚刚试了下 好像不是后台的原因 我现在看看 不好意思 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
不好意思 现在已经可以了。出现你那个报错是因为git修改文件大小写是不识别的，Login单文件组件原先是小写 后来被我改成大写以后git add的时候不会识别，所以路由的时候会出问题。

**Comment by q793809050** [comment]
....&nbsp;发送看到了放到了一大堆发请求那里了 不好意思 这波我的&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Lil-C0der"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月30日(星期四) 晚上6:50
收件人:&nbsp;"Lil-C0der/Vue_CMS"<Vue_CMS@noreply.github.com&gt;;
抄送:&nbsp;"QQ邮箱"<793809050@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Lil-C0der/Vue_CMS] 问题 (#1)





  
To install it, you can run: npm install --save views/login/Login &nbsp;我是第一次看见这个东西的 你的是文件呀 也不是包 叫下载&nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Lil-C0der"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月30日(星期四) 晚上6:34 收件人:&nbsp;"Lil-C0der/Vue_CMS"<Vue_CMS@noreply.github.com&gt;; 抄送:&nbsp;"QQ邮箱"<793809050@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Lil-C0der/Vue_CMS] 问题 (#1) 兄弟 为什么我下载下来运行不了呢 说要下载登录页 不懂了 我刚刚试了下 好像不是后台的原因 我现在看看 不好意思 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
不好意思 现在已经可以了。出现你那个报错是因为git修改文件大小写是不识别的，Login单文件组件原先是小写 后来被我改成大写以后git add的时候不会识别，所以路由的时候会出问题。

**Comment by Lil-C0der** [comment]
可以clone一下最新的代码 应该已经没问题了。有些错误我自己都没有发现，谢谢你哈

**Comment by q793809050** [comment]
兄弟 问个问题 你的代码里面虽然是组件化了 很多都是基于你自己二次的封装 但是你这样最后的代码量就多了很多 我直接拿element里面的实现 不实现二次封装 代码量就少了很多 哪个会更好一下的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Lil-C0der"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月3日(星期天) 凌晨1:44
收件人:&nbsp;"Lil-C0der/Vue_CMS"<Vue_CMS@noreply.github.com&gt;;
抄送:&nbsp;"QQ邮箱"<793809050@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Lil-C0der/Vue_CMS] 问题 (#1)





 
Closed #1.

**Comment by q793809050** [comment]
兄弟 问个问题 你的代码里面虽然是组件化了 这个做法挺好的 我也很喜欢 很多都是基于你自己二次的封装 但是你这样最后的代码量就多了很多 我直接拿element里面的实现 不实现二次封装&nbsp; 就是单页的代码看起来会臃肿一些 但是这样代码量就少了很多 哪个会更好一下的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Lil-C0der"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月3日(星期天) 凌晨1:44
收件人:&nbsp;"Lil-C0der/Vue_CMS"<Vue_CMS@noreply.github.com&gt;;
抄送:&nbsp;"QQ邮箱"<793809050@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Lil-C0der/Vue_CMS] 问题 (#1)





 
Closed #1.

**Comment by Lil-C0der** [comment]
> 兄弟 问个问题 你的代码里面虽然是组件化了 这个做法挺好的 我也很喜欢 很多都是基于你自己二次的封装 但是你这样最后的代码量就多了很多 我直接拿element里面的实现 不实现二次封装&nbsp; 就是单页的代码看起来会臃肿一些 但是这样代码量就少了很多 哪个会更好一下的
> […](#)

这个问题我觉得看个人吧。我觉得一个组件最好还是处理一个逻辑吧，否则很多逻辑堆在一个组件里面 可能开发和维护时会比较费劲，其实我觉得我的封装还是有一些不足，有些地方并不是那么完美。

**Comment by q793809050** [comment]
兄弟 需要解释一下 你这代码有点深奥&nbsp; 一个是公共组件面包屑&nbsp; 然后一个是子组件 你这样就能用这个数据的?我不太明白 很深奥 求细解
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Lil-C0der"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月7日(星期四) 上午9:19
收件人:&nbsp;"Lil-C0der/Vue_CMS"<Vue_CMS@noreply.github.com&gt;;
抄送:&nbsp;"QQ邮箱"<793809050@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Lil-C0der/Vue_CMS] 问题 (#1)





 
Reopened #1.

**Comment by Lil-C0der** [comment]
面包屑那块写的确实有点乱，等有空了可能会重写一下。

主要是通过侧边栏点击的时候来获取两个菜单的文本，通过Vuex来保存。但是光用vuex的话刷新就会消失，所以在sessionStorage里面又存了一次。
现在有一个bug就是直接用路径访问的时候可能会有点问题。之前我没有引入Vuex的时候用的是路由守卫+sessionStorage来做的，那样就不会有bug 过段时间可能会改下这个bug
